version: "3.4"
services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mybucket
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000 # MinIO API port
      - 9001:9001 # MinIO Console port
volumes:
  minio_data: